version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      ENABLE_RCON: "true"
      RCON_PORT: 28016
      VERSION: "1.19.2"
    tty: true
    stdin_open: true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - traefik.tcp.routers.papermc.rule=HostSNI(`*`)
      - traefik.tcp.routers.papermc.entrypoints=minecraft
    networks:
      proxy:
        ipv4_address: 10.200.15.2

volumes:
  mc:
  rcon:

networks:
  proxy:
    external: true
